# Generated by Django 2.0.7 on 2018-07-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20180703_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='unique_words',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
